# Generated by Django 4.2.2 on 2023-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='username',
            new_name='name',
        ),
    ]
